-- Create wallets table
CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    currency VARCHAR(10) NOT NULL,
    balance BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_currency UNIQUE (user_id, currency)
);

-- Create ledger_entries table
CREATE TABLE IF NOT EXISTS ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES wallets(id),
    reference BIGINT NOT NULL, -- Reference to the external transaction
    type VARCHAR(50) NOT NULL,     -- e.g., 'credit', 'debit'
    amount BIGINT NOT NULL,
    balance BIGINT NOT NULL,       -- Balance of the wallet after this entry
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);